@extends('layouts.layout')

@section('content')

<!-- #Content -->
<div class="g1-column g1-column-2of3">
				<div class="entry-content" itemprop="text">
					<p>Adsonmedia<br>
Last Updated: January 29, 2016</p>
<ol>
<li><strong>Your Acceptance.</strong><br>
<strong>1.By visiting or using a website or application owned or controlled by Adsonmedia, including our affiliated companies (collectively, “Adsonmedia” or “we” or “our” or “us”), or any our products, software, data feeds, video player and services provided to you by Adsonmedia (collectively the “Service”) you signify your agreement to: (I) these terms and conditions (the “Terms of Service”); and (II) our <a href="{{ url('/privacy') }}">Privacy Policy</a>&nbsp;(the “Privacy Policy”), and incorporated herein by reference. If you do not agree to any of these terms or the Privacy Policy, please do not use the Service.</strong><br>
<strong>2.Although we may attempt to notify you when major changes are made to these Terms of Service, you should periodically review the most up-to-date version. We may, in our sole discretion, modify or revise these Terms of Service and policies at any time, and you agree to be bound by such modifications or revisions. Nothing in these Terms of Service shall be deemed to confer any third-party rights or benefits.</strong></li>
<li><strong>Service.</strong><br>
<strong>1.These Terms of Service apply to all users of the Service, including users who are also contributors of Content on the Service. “Content” includes the text, software, scripts, graphics, photos, sounds, music, videos, audiovisual combinations, interactive features and other materials you may view on, access through, or contribute to the Service.</strong><br>
<strong>2.Certain products, services, features, functionality, and content made available by us on the Service are delivered by third parties. By accessing or using any product, service, feature, functionality, or content originating from the Service, you hereby acknowledge and consent that we may share information and data with third parties with whom we have a contractual relationship to provide the requested product, service, feature, functionality, or content for our users.</strong><br>
<strong>3.The Service may contain links to third party websites that are not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, we will not and cannot censor or edit the content of any third-party website. By using the Service, you expressly relieve Adsonmedia from any and all liability arising from your use of any third-party website.</strong><br>
<strong>4.Accordingly, we encourage you to be aware when you leave the Service and to read the terms and conditions and privacy policy of each other website that you visit.</strong></li>
<li><strong>Accounts and Third Party Accounts.</strong><br>
<strong>1.In order to access some features of the Service, you will have to create an account. You may never use another user’s account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. You must notify us immediately of any breach of security or unauthorized use of your account.</strong><br>
<strong>2.Although we will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Adsonmedia or others due to such unauthorized use.</strong><br>
<strong>3.You may be able to connect your account on our Service to your third party accounts on other services (e.g., Facebook or Twitter). By connecting your account to your third party accounts, you acknowledge and agree that you are consenting to the continuous release of information about you to others (in accordance with your privacy settings on those third party sites). If you do not want information about you to be shared in this manner, do not use this feature.</strong><br>
<strong>4.General Use of the Service – Permissions and Restrictions.</strong><br>
We hereby grant you permission to access and use the Service as set forth in these Terms of Service, provided that:</li>
</ol>
<p><strong>&nbsp; &nbsp; 1.You agree not to distribute in any medium any part of the Service or the Content without our prior written authorization, unless we make available the means for such distribution through functionality offered by the Service, such as with an embeddable video player authorized by us (“Embeddable Player”) or other authorized means that we may designate.</strong><br>
<strong>&nbsp;2.You agree not to alter or modify any part of the Service.</strong><br>
<strong>3.You agree not to access Content through any technology or means other than on the Service itself, an Embeddable Player, or other explicitly authorized means we may designate.</strong><br>
<strong>4.You agree not to use the Service for any of the following commercial uses unless you obtain our prior written approval:</strong></p>
<ul>
<li><strong>the sale of access to the Service;</strong></li>
<li><strong>the sale of advertising, sponsorships, or promotions placed on or within the Service or Content; or</strong></li>
<li><strong>the sale of advertising, sponsorships, or promotions on any page of an ad-enabled blog or website containing Content delivered via the Service, unless other material not obtained from us appears on the same page and is of sufficient value to be the basis for such sales.</strong><br>
<strong>5.Prohibited commercial uses do not include:</strong></li>
<li><strong>uploading an original video to the Service, or maintaining an original channel on the Service, to promote your business or artistic enterprise;</strong></li>
<li><strong>showing our videos through an Embeddable Player on an ad-enabled blog or website, subject to the advertising restrictions set forth herein; or</strong></li>
</ul>
<p><strong>any use that we expressly authorize in writing.</strong><br>
<strong>6.If you use an Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the Service.</strong><br>
<strong>7.You agree not to use or launch any automated system, including without limitation, “robots,” “spiders,” or “offline readers,” that accesses the Service in a manner that sends more request messages to the Service’s servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. Notwithstanding the foregoing, we grant the operators of public search engines permission to use spiders to copy materials from the website for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials. We reserve the right to revoke these exceptions either generally or in specific cases. You agree not to collect or harvest any personally identifiable information, including account names, from the Service, nor to use the communication systems provided by the Service (e.g., comments, email) for any commercial solicitation purposes. You agree not to solicit, for commercial purposes, any users of the Service with respect to their Content.</strong><br>
<strong>8.In your use of the Service, you will comply with all applicable laws.</strong><br>
<strong>9.We reserve the right to discontinue any aspect of the Service at any time.</strong></p>
<p><strong>5.Your Use of Content.</strong><br>
In addition to the general restrictions above, the following restrictions and conditions apply specifically to your use of Content.</p>
<ol>
<li><strong>The Content on the Service, and the trademarks, service marks and logos (“Marks”) on the Service, are owned by or licensed to Adsonmedia, subject to copyright and other intellectual property rights under the law.</strong></li>
<li><strong>Content is provided to you AS IS. You may access Content for your information and personal use solely as intended through the provided functionality of the Service and as permitted under these Terms of Service. You shall not download any Content unless you see a “download” or similar link displayed by us on the Service for that Content. You shall not copy, reproduce, distribute, transmit, broadcast, display, sell, license, or otherwise exploit any Content for any other purposes without the prior written consent of us or the respective licensors of the Content. Adsonmedia and its licensors reserve all rights not expressly granted in and to the Service and the Content.</strong></li>
<li><strong>You agree not to circumvent, disable or otherwise interfere with security-related features of the Service or features that prevent or restrict use or copying of any Content or enforce limitations on use of the Service or the Content therein.</strong></li>
<li><strong>You understand that when using the Service, you will be exposed to Content from a variety of sources, and that we are not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Content. You further understand and acknowledge that you may be exposed to Content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against us with respect thereto, and, to the extent permitted by applicable law, agree to indemnify and hold harmless Adsonmedia, its owners, operators, affiliates, licensors, and licensees to the fullest extent allowed by law regarding all matters related to your use of the Service.</strong></li>
</ol>
<p><strong>6.Your Content and Conduct.</strong></p>
<ol>
<li><strong> As an account holder you may be able to submit Content to the Service, including videos and user comments. You understand that we do not guarantee any confidentiality with respect to any Content you submit.</strong></li>
<li><strong>You shall be solely responsible for your own Content and the consequences of submitting and publishing your Content on the Service. You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish Content you submit; and you license to Adsonmedia all patent, trademark, trade secret, copyright or other proprietary rights in and to such Content for publication on the Service pursuant to these Terms of Service.</strong></li>
<li><strong>For clarity, you retain all of your ownership rights in your Content. However, by submitting Content to the Service, you hereby grant Adsonmedia a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the Content in connection with the Service and Adsonmedia’s (and its successors’ and affiliates’) business, including without limitation for promoting and redistributing part or all of the Service (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each user of the Service a non-exclusive license to access your Content through the Service, and to use, reproduce, distribute, display and perform such Content as permitted through the functionality of the Service and under these Terms of Service. The above licenses granted by you in video Content you submit to the Service terminate within a commercially reasonable time after you remove or delete your videos from the Service. You understand and agree, however, that we may retain, but not display, distribute, or perform, server copies of your videos that have been removed or deleted. The above licenses granted by you in user comments you submit are perpetual and irrevocable.</strong></li>
<li><strong>You further agree that Content you submit to the Service will not contain third party copyrighted material, or material that is subject to other third party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to post the material and to grant us all of the license rights granted herein.</strong></li>
<li><strong>You further agree that you will not submit to the Service any Content or other material that is contrary to these Terms of Service or contrary to applicable local, national, and international laws and regulations.</strong></li>
<li><strong>We do not endorse any Content submitted to the Service by any user or other licensor, or any opinion, recommendation, or advice expressed therein, and we expressly disclaim any and all liability in connection with Content. We do not permit copyright infringing activities and infringement of intellectual property rights on the Service, and we will remove all Content if properly notified that such Content infringes on another’s intellectual property rights. We reserve the right to remove Content without prior notice.</strong></li>
<li>&nbsp;Use of Communication Services.</li>
</ol>
<p>a. &nbsp;The Service may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication services designed to enable you to communicate with the public at large or with a group (collectively, “Communication Services”), you agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service.</p>
<p>b. &nbsp;By way of example, and not as a limitation, you agree that when using a Communication Service, you will not: defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others; publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information; upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents; upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another’s computer; advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages; conduct or forward surveys, contests, pyramid schemes or chain letters; download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner; falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, restrict or inhibit any other user from using and enjoying the Communication Services; violate any code of conduct or other guidelines which may be applicable for any particular Communication Service; harvest or otherwise collect information about others, including e-mail addresses, without their consent; violate any applicable laws or regulations.</p>
<p>c. &nbsp;We have no obligation to monitor the Communication Services. However, we reserve the right to review materials posted to a Communication Service and to remove any materials in our sole discretion. We reserve the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</p>
<p>d. &nbsp;We reserve the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in our sole discretion.</p>
<p>e. &nbsp;Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. We do not control or endorse the content, messages or information found in any Communication Service and, therefore, we specifically disclaim any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized Adsonmedia spokespersons, and their views do not necessarily reflect those of Adsonmedia.</p>
<p>f. &nbsp;Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you upload the materials.</p>
<p>8. &nbsp;Account Termination Policy.</p>
<ol>
<li>We will terminate a user’s access to the Service if, under appropriate circumstances, the user is determined to be a repeat infringer.</li>
<li>We reserve the right to decide whether Content violates these Terms of Service for reasons other than copyright infringement, such as, but not limited to, pornography, obscenity, or excessive length. We may at any time, without prior notice and in our sole discretion, remove such Content and/or terminate a user’s account for submitting such material in violation of these Terms of Service.</li>
</ol>
<p>9. &nbsp;Digital Millennium Copyright Act.</p>
<ol>
<li><strong>If you are a copyright owner or an agent thereof and believe that any Content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</strong></li>
</ol>
<ul>
<li><strong> A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</strong></li>
<li><strong>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</strong></li>
<li><strong>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</strong></li>
<li><strong>Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;</strong></li>
<li><strong>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</strong></li>
<li><strong>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</strong></li>
</ul>
<p><strong>2.Our designated Copyright Agent to receive notifications of claimed infringement is:</strong></p>
<p>Adsonmedia</p>
<p>Attn: General Counsel</p>
<p><a href="mailto: info@adsonmedia.ae">copyright@adsonmedia.ae</a></p>
<p>For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to Adsonmedia customer service. You acknowledge that if you fail to comply with all of the requirements of this Section 9, your DMCA notice may not be valid.</p>
<p><strong>3.If you believe that your Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to post and use the material in your Content, you may send a counter-notice containing the following information to the Copyright Agent:</strong></p>
<ul>
<li><strong>Your physical or electronic signature;</strong></li>
<li><strong>Identification of the Content that has been removed or to which access has been disabled and the location at which the Content appeared before it was removed or disabled;</strong></li>
<li><strong>A statement that you have a good faith belief that the Content was removed or disabled as a result of mistake or a misidentification of the Content; and</strong></li>
<li><strong>Your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the federal court in Los Angeles, California, and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</strong><br>
<strong>4.If a counter-notice is received by the Copyright Agent, we may send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed Content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the Content provider, member or user, the removed Content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at our sole discretion.</strong></li>
</ul>
<p>10. Warranty Disclaimer.</p>
<p>YOU AGREE THAT YOUR USE OF THE SERVICES SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, ADSONMEDIA, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF. ADSONMEDIA MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS WEBSITE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THIS WEBSITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY: (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICES; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES; (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY; AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. ADSONMEDIA DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND ADSONMEDIA WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
<p>11. Limitation of Liability.</p>
<p>IN NO EVENT SHALL ADSONMEDIA, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY: (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICES; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES; (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY; AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. YOU SPECIFICALLY ACKNOWLEDGE THAT ADSONMEDIA SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. IN NO EVENT WILL ADSONMEDIAS’ TOTAL AGGREGATE LIABILITY TO YOU UNDER THESE TERMS OF SERVICE EXCEED THE AMOUNT PAID BY YOU TO USE THE SERVICE.</p>
<p>The Service is controlled and offered by Adsonmedia from its facilities in the United States of America. Adsonmedia makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>
<p>12. Indemnification.</p>
<p>To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless Adsonmedia, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (I) your use of and access to the Service; (II) your violation of any term of these Terms of Service; (III) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (IV) any claim that your Content caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the Service.</p>
<p>13. Ability to Accept Terms of Service.</p>
<p>You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. In any case, you affirm that you are over the age of 13, as the Service is not intended for children under 13. If you are under 13 years of age, then please do not use the Service. Talk to your parents about what websites are appropriate for you.</p>
<p>14. Assignment.</p>
<p>These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Adsonmedia without restriction.</p>
<p>15. General.</p>
<p>You agree that: (I) the Service shall be deemed solely based in California; and (II) the Service shall be deemed a passive website that does not give rise to personal jurisdiction over Adsonmedia, either specific or general, in jurisdictions other than California. These Terms of Service shall be governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles. Any claim or dispute between you and Adsonmedia that arises in whole or in part, directly or indirectly, from these Terms of Service or the <a href="http://viralnovae.com/privacy-policy/">Privacy Policy</a>&nbsp;or your use of the Service shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws rules applicable to contracts to be performed entirely within the State of California, Los Angeles County. For all such matters, each party irrevocably submits to the exclusive jurisdiction of JAMS Arbitration in the County of Los Angeles, State of California and waives any jurisdictional, venue, or inconvenient forum objections to such arbitration. These Terms of Service, together with the Privacy Policyand any other legal notices published by us on the Service, shall constitute the entire agreement between you and Adsonmedia concerning the Service. If any provision of these Terms of Service is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. No waiver of any term of this these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and Adsonmedia’s failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision. We reserve the right to amend these Terms of Service at any time and without notice, and it is your responsibility to review these Terms of Service for any changes. Your use of the Service following any amendment of these Terms of Service will signify your assent to and acceptance of its revised terms. YOU AND ADSONMEDIA AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
<p>16. Notice for California Users.</p>
<p>Under California Civil Code Section 1789.3, California users of the online services are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 400 R Street, Suite 1080, Sacramento, California 95814, or by telephone at (916) 445-1254 or (800) 952-5210.</p>
<p>17. Contact Information.</p>
<p>If you have any questions regarding these Terms of Service, you may email us at <a href="mailto: info@adsonmedia.ae">contact@adsonmedia.ae</a> or contact us by mail addressed to:</p>
<p>Adsonmedia</p>
<p>Effective Date of these Terms of Service</p>
<p>These Terms of Service are effective as of June 24, 2011 and last updated January 29, 2016.</p>
				</div><!-- .entry-content -->
			</div>

<!-- content end -->

    @stop